- name: Gather facts
  ubus: cmd=facts

- name: Check whether opkg caches need update
  raw: date +%s -r /tmp/opkg-lists
  register: _opkg_epoch
  check_mode: false
  changed_when: false
  failed_when: false

- name: Get current system time
  raw: date +%s
  register: _epoch
  check_mode: false
  changed_when: false
  when: _opkg_epoch.rc == 0

- name: Update opkg cache
  opkg:
    name: opkg
    update_cache: yes
  register: _update
  when: _opkg_epoch.rc != 0 or
      _epoch.stdout|int - _opkg_epoch.stdout|int > 86400
  changed_when: not _update.failed

- name: Install dependencies for file-related modules
  opkg: pkg=luaposix,coreutils-sha1sum state=present
